### PR TITLE
Rewrote your shitty plugin

### PR DESCRIPTION
**Pull request by iiFlamiinBlaze**
Oof I couldn't look at this plugin, it was so shitty. So I fixed it. Your welcome :D

### CODE REVIEW

**Comment by DaPigGuy** [comment]
👍 Looks great. Removed useless imports, removed the unnecessary Listener class, cleared armor inventory,  fixed the README, fixed the messy config.yml, fixed idioticly adding 4.0.0 to supported api versions, cleaned up code, added a new override permission. Wonderful!

**Comment by DarkWav** [comment]
I first tried to not use EventListener but it has prooven to not work in my Testing. Thanks for the Armor iten notice, might actually Change that.
And please use more apporopriate language :/
Closed.

**Comment by DaPigGuy** [comment]
Just because you couldn't get it to work yourself doesn't mean this doesn't work... Try testing it before closing.

**Comment by iiFlamiinBlaze** [comment]
Maybe try actually being a good developer? Lmao this plugin is terrible before this PR, I would recommend merging it.

**Comment by DarkWav** [comment]
I am actually willing to merge most of this pr, but i wont remove EventListener (explained below)
@iiFlamiinBlaze Most of your ideas are really good, but please be more respectfull about other people and their work.
@DaPigGuy I tested a lot and it did not work for me. I probably made a mistake that i couldn't figure out, but if my EventListener works i think that ok because I see no reason why _**not**_ to make an EventListener as it makes everything more organized IMO, thats why I want to keep the EventListenr and do not directly merge the PR. (But this comes down to personal prefrence)
Parts of the PR will be merged and both of you will be honored as an Author. (in plugin.yml and readme.md)

**Comment by iiFlamiinBlaze** [comment]
Lmao, you could have just merged this PR. Since obviously my PR is so much better than your "Merge PR" commit lmao. Also my PR works lmao

**Comment by DaPigGuy** [comment]
You tested a lot huh...

**Comment by DaPigGuy** [comment]
Oh also you still have a lot of useless imports, especially in your Listener class.

**Comment by DarkWav** [comment]
Seeing People rage is Fun :P @DaPigGuy i will fix some more useless imports, thanks for the Info

**Comment by iiFlamiinBlaze** [comment]
We aren't raging, I just wasted my time making this plugin better for you to half-ass merge it lmao

**Comment by DarkWav** [comment]
Insults are not permitted here. Try Again. :)

**Pull request closed without merging**
